services:
  mysql_test:
    image: mysql:8.3
    container_name: kmp-mysql-test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kmp_db
      MYSQL_USER: kmp_user
      MYSQL_PASSWORD: kmp_password
    ports:
      - "3309:3306"
    volumes:
      - mysql_data_test:/var/lib/mysql

volumes:
  mysql_data_test:
